language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: uyMoDSDXHXAHXABXBaRxAd8wxCUobTFv6aWeY9n4Aya0/GjHkiMelwdQ4e/gzbEz0Y8I1L1KkDQnHIuq4WvTf5w+bOVDY8lOm1S3wl4iDm+rpvY3Itd97Ml/iH0wiwu3BFDwvdbUA1sgq2UFGnSwrDU04VtYMejuzdzpDOBgeE748hHDpfot2erw//H81w2YAvvFk7IG7foR48KfVrzuCPwKEpJbZP24s085xN4eVrk4J68FOIqVs3fBJsfi9GqmgjLpnUAkOnjcppOaqi61kuS/GJIFs9AyHPvb38OHMf4B8eB6GtfxTcj9HewQbwyKJEt7zckUslieJggmL5mReFGirPEQgRA3wvXfJ2NOwJBHnpfcenB+c/wZKcXFj47ug+gzzoFafy7pFlYgLBwu744oJ83edaw3/H9+M8l0oyyQdNEV7NMwv8qMYKzCsBkzumsHakIzqHwwDN/FRYGSTCVrFpzYEr6U0IJEAlIsI5AntCeqfAbHWMJVvJyofqtFwXAZbKWrMG6cD0SlZ+XhczEYosEST+McLKLaHgbbCZLTuwJo/vtWhzFRNhT3N0kgjJtz+mo1CfixyKlcoTJbBdizJFp29n62EWsTk8zzKf3VY/vXKNX+w9h6No1si5jWt8Kphx7NiIe4188IOLtk+HHmiy79FJjPZPwer2vGrEQ=
  - secure: ASaznj0RLkkKNgfP/eBTWjAgWUC2dPQC5r0+T6zgG9ZSdwCWwFBv+zppiMmOA27NiWlx0Toag9rTiRn4VQijgOZ3UySmOO5YGJiZ5PrhXUljzS/KaIWduwJ965bQPDD+pgWeC0PXfUTtpwUb9zs2GRfZQCGV2SZ6T9lDTtymeBxIQFDsRqb7itx1YM47AbrhmNmP9KbyJEWez15GAIGAZS8l2E+Fmi5ahOLUATU7UEQkz/mm4BNBUQ5KNZfV0/pKAi4yZZm0DqPnLHJS+OxIzOJ2GyzdRWeoMxfYtjqqwc7+senEQ9tIxowvMnAfTIVkdIWU9IQd89Jkeqp+tlDYyrCxyN6ufqiVtbiBg4FpkB0dTApbElUDU7TlJu5aPiXs/4Iwnsvj1suzFLa6HNseJ+H6S2wvyP7O9ogimrRxhdX2OY8NYwv+niAfCTBG58L+2F8pkbOX/LmA6tsfGaqIr9tynp5zT803oZ9oSd0azUvAEPyogZF5467PrGXY0nUrK/QsvSXvH5GTs78oPYOxCwfV0a+H0+j20gnxj9la6XX8Jp+W+DVZaehVnQ80dbVRH90LTIZW2xCkJTK6NyV0MSC4Y+xsTwByMNeHSfd8z9siZljSqehtH5Gw8Xqr/+HTJFu29mA0Dur+wV4k7PO7eNeuDwDHuJt0jTPw+x/EIdE=
